services:
  - type: web
    name: blanch-family
    runtime: node
    plan: free
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: DISCORD_REDIRECT_URI
        sync: false
